### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by DomVinyard** [willyelm/atom-bugs#1]
This looks fantastic. Congrats. Any chance you could include a first-time setup guide? I'm new to node-debugging, running my script via the terminal as usual but the breakpoints don't get hit.

**Comment by willyelm** [comment]
if you started the process from a terminal instance you need to run your script using the flag `--debug-brk=5858` or the port you desire to use. on you atom editor:
1. click the scheme button by default should be "Current File" it will open the scheme editor
2. on the scheme editor select the tab "Remote"
3. in the port field inside remote section put the port you are using in the case: 5858
4. close the editor and press the run button beside the scheme button.

your breakpoints will be hit now. it is more compatible if you start your application using the workspace scheme configuration. which would look something like the attachment

<img width="600" alt="screen shot 2016-08-12 at 11 02 30 am" src="https://cloud.githubusercontent.com/assets/1202219/17626695/54f03106-607c-11e6-8ec3-a3a390bdd8eb.png">
- watch files will restart the process wherever you make a change on files that match the rule.

Hope it helps, thanks for the feedback let me know if I could help you in something else.

**Comment by DarrylD** [comment]
Maybe something like this should be in the readme? Looks awesome based on the gif of it in use but, having a hard time getting it up and running. A 1 min video tut would be amazing 😊

**Comment by dkebler** [comment]
hmmm...  I'm using a cli module vorpal to control the flow of my code.   I set the workspace like in the snapshot above, go into my code and set a breakpoint,  then start with  `"node --debug=5858 4s.js"` from the terminal.  Then I give a cli command that will enter the code where the breakpoint is set and .....it blows right by :-(.   Any suggestions and what else to try before I start posting my code?

**Comment by dkebler** [comment]
FYI for newbies,  just needed to click the little green arrow next  to the "scheme button"/"workspace" that would be step 4 duh.  So ya little video would help will getting all the steps.   So Thx best easiest atom javascript debugger I've tried.

**Comment by willyelm** [comment]
Hi dkebler, I'll try to create a video showing how to setup today, thanks for the feedback

**Comment by yamsellem** [comment]
@willyelm I'm having hard times too, starting up your debugger.

In your [12 August step by step readme](https://github.com/willyelm/atom-bugs/issues/1#issuecomment-239470788), you advice to open the "remote" tab, but your screenshot shows the "workspace" tab. So which is the good one?

Plus, none of them work here.

I start a server with `--debug=5858` or `--debug-brk=5858` and then start the debugger.
But the server stays in a `Debugger listening on [::]:5858` state forever.

Thanks a lot for your help.

_ps. I think a video is a lot of work for such a thing. A clear step by step with an express server (or other) is plenty to explain how to start. And an example with a mocha unit test will be highly appreciated / of great help._

_ps. once the remote is launched, is cannot be stop — have to restart atom to_

_ps. may I gently ask on option to show the debugger at the bottom of atom? Seems more classic, compared to what chrome does ;-)_

Node 6.9.1.
Atom 1.13.1
Atom Bugs 0.24.0

**Comment by yamsellem** [comment]
@willyelm So, after some digging, the "workspace" tab works perfectly.
I've configured the "script file path" and "watch files" and it starts the server in a debug mode.
With this, no need of a terminal.

The remote work too.
Starting node with `--debug=5858` in a terminal and then, starting the plugin works great. But the "resume", "step over" & co arrows don't seems to work (_the "resume" give the hand back, but that's all_). It seems that the current line is not known.
