### ISSUE TITLE
Deprecated selector in `atom-bugs/styles/bugs.less`

### ISSUE THREAD

**Issue by JasonSooter** [willyelm/atom-bugs#17]
In `atom-bugs/styles/bugs.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .bugs-line-breakpoint,
atom-text-editor::shadow .bugs-line-breakpoint` => `atom-text-editor .bugs-line-breakpoint,
atom-text-editor.editor .bugs-line-breakpoint`

* `atom-text-editor .bugs-line-breakpoint.cursor-line,
atom-text-editor::shadow .bugs-line-breakpoint.cursor-line` => `atom-text-editor .bugs-line-breakpoint.cursor-line,
atom-text-editor.editor .bugs-line-breakpoint.cursor-line`

* `atom-text-editor .bugs-line-breakpoint:after,
atom-text-editor::shadow .bugs-line-breakpoint:after` => `atom-text-editor .bugs-line-breakpoint:after,
atom-text-editor.editor .bugs-line-breakpoint:after`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by willyelm** [comment]
fixed on atom-bugs@v0.20.0
