### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by yamsellem** [willyelm/atom-bugs#18]
Hi,

Thanks a LOT for your debugging plugin, it's great!

I've got some little ideas on small UX improvements that could greatly help, maybe you'll find them useful too.

**Highlighting current line**
When entering in debug, the current line is selected but not highlighted, using atom selected line color would more clearly mark where the code is stopped

Turning this:
![without highlighted](https://cloud.githubusercontent.com/assets/606754/22701797/0416ef34-ed5f-11e6-803d-6e27faf534ae.png)

Into this:
![highlighted](https://cloud.githubusercontent.com/assets/606754/22701681/a00ca2e0-ed5e-11e6-9ad0-b1e3968ea452.png)

**Displaying object properties**
When focusing on a variable, it is displayed as is it was independent of its object. Focusing on the `name` of  `this.value.name` will display `name` as is it was an independent variable. One has to focus on the entire variable, so `this.value.name`, to grab its value.

Plus, it would be great if a mouseover does the same (as in chrome).

Instead of this:
![unlinked variable](https://cloud.githubusercontent.com/assets/606754/22702179/201cb582-ed60-11e6-8207-02a6a3895854.png)

Display this:
![linked propertie](https://cloud.githubusercontent.com/assets/606754/22702182/249577ac-ed60-11e6-94d3-7701657513b6.png)

**Configuring the debugger position**
Having the choice to position the debugged at the top or bottom of atom would be great! (Chrome has made a classic way of debugging at the bottom).

Plus, it can be cool to hide the debugger, sometimes (having to disable it to hide it seems, hum, extreme ;-).

**Comment by yamsellem** [comment]
@willyelm is it possible to have a status on this? Please ;-)

**Comment by willyelm** [comment]
Hi @yamsellem, I am about to release version 1 which will include that feature.

**Comment by willyelm** [comment]
the features described on the issues have been added on the latest version. https://atom.io/packages/atom-bugs

- Highlight breakpoint line
- Auto inspect variable words on mouse enter
- Toggle debugging panel command

Please note atom-bugs has been moved to another repository https://github.com/atom-bugs/atom-bugs. 
Thank you for your feedback!.
