### ISSUE TITLE
Remote Debugging not working

### ISSUE THREAD

**Issue by whateverforever** [willyelm/atom-bugs#5]
Hey there,
I have an Electron app running, with `--remote-debug-port` enabled. I can access the debug port via chrome: `127.0.0.1:5858`. Sadly however, I can't connect to it using atom-bugs. The green playbutton simply does nothing (With Scheme `Remote` set to the same parameters as chrome). Also the console inside Atom doesn't say anything.

I'm using `electron-prebuilt@1.4.2`,`Atom 1.11.2` and `Node 4.2.2`

Great project though, would love to see this become big :)

**Comment by whateverforever** [comment]
Could it be a missing `.on('connect')`? How do you catch once the debugger is connected?

**Comment by jbrosan** [comment]
Hi, 

I'm new to Atom. Currently using WebStorm, but would like to change over 100% Atom. I've installed the plugin, and would like to debug a node.js application (uses Loopback.io) is there documentation on what I need to do after I install atom-bugs? I have no idea what do do next as there are no settings.

Any assistance would be most appreciated.

**Comment by Apollon77** [comment]
I experience the same problem. When I click on the green play button with "remote" scheme the button changes to the red-stop-signal, but nothing more happends. ALso clicking the red stop sign do not end the session ...
Would be great to see that working :-)

**Comment by nottix** [comment]
Same error here

**Comment by leonardodelfino** [comment]
same error

**Comment by tinylit** [comment]
Same error here.

**Comment by willyelm** [comment]
Please try with the latest version which has been moved here: https://github.com/atom-bugs/atom-bugs
